name: Pedro Allende
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: Insert Title Here. Seriously.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69199446-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a1a18'
    - '#bc9061'
    - '#d1d5d6'
    - '#444349'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
